server:
  port: ${PORT:18888}
spring:
  application:
    name: sentinel-flow-example
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080                            '


